# Generated by Django 4.2.10 on 2024-03-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granate_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'Opportunity',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
                ('photo', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
