# Generated by Django 4.2.10 on 2024-02-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granate_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
